language: rust
services:
  - mongodb
before_install:
  # Install Node.js
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
script:
  - cd $TRAVIS_BUILD_DIR/evelyn/backend && ./scripts/run_tests.sh
  - cd $TRAVIS_BUILD_DIR/evelyn/test/server_integration_tests/ && ./run_tests.sh
