[project]

name = "evelyn"
version = "0.0.1"
authors = ["Gregory Jensen <greatdjonfire@hotmail.co.uk>"]

[dependencies]
serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"

bson = "0.4.3"
mongodb = "0.2.2"

jsonwebtoken = "1"
rustc-serialize = "0.3"

chrono = { version = "0.3", features = ["serde", "rustc-serialize"] }

[dependencies.config]
version = "0.4"
default-features = false
features = ["yaml", "yaml-rust"]

[dev-dependencies]
hyper = "0.10.5"
