array_layout  = "Block"
generics_indent = "Block"
match_block_trailing_comma = true
reorder_imported_names = true
wrap_comments = false
format_strings = false
indent_match_arms = true
max_width = 200
trailing_comma = "Always"
# control_brace_style = "ClosingNextLine" see rustfmt#1377

space_after_bound_colon = true
space_after_type_annotation_colon = true
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false

struct_lit_multiline_style = "ForceMulti"
struct_lit_style = "Block"

fn_brace_style = "PreferSameLine"
fn_args_layout = "Block"
fn_args_density = "Vertical"

hard_tabs = false
tab_spaces = 4

write_mode = "Overwrite"
